### ISSUE TITLE
Y24-234 As a CASM Project Mgr (LH) I would like the data access groups to be shown in a new column appended to the sample tracking report so that we can easily filter on studies of interest to us.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/sample-tracking#22]
As a CASM Project Mgr (LH) I would like the data access groups to be shown in a new column appended to the sample tracking report so that we can easily filter on studies of interest to us.

**Acceptance Criteria**

- [x] A new column append to the end of the _sample_tracking_view_ in mlwh_reporting called "data access groups" that is populated from the study table data_access_group column
- [x] The Tableau report to be updated with the new column from the view.
- [x] The search functionality in Tableau to search entries in this column when searching by "All"

**Comment by sabrine33** [comment]
UAT Tableau Dashboard: 
https://globalreporting.internal.sanger.ac.uk/#/views/SampleTrackingV2/SampleTrackingv22?:iid=2
