### ISSUE TITLE
Y24-239 As a CASM Project Mgr (LH) I would like the bait capture library name to be displayed on the Sample Tracking Report so that we can analyse the results quickly.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/sample-tracking#23]
As a CASM Project Mgr (LH) I would like the bait capture library name to be displayed on the Sample Tracking Report so that we can analyse the results quickly.

**Additional Context**
Bait libraries are selected and entered into SequenceScape when making a sequencing request.

The bait ids are stored in the `iseq_flowcell` table `bait_name` column (may be NULL).

Therefore these bait ids will need aggregating when displaying on a stock plate per row basis as in the Sample Tracking View. I would suggests starting with a distinct concatenation along the lines of the other aggregated columns.

There may be no or NULL bait library.

**Acceptance Criteria**
 

- [x] An additional column "bait_names" in sample_tracking_view in the mlwh_reportign database is added to the right of the 'library_type' column.
- [x] Run the `./apply.py --uat views/sample_tracking_view.sql` script to add the column to the database view
- [x] Tableau should run at 2am, to pull the latest view into the Tableau report
- [x] In Tableau, rename field from `bait_names` to `Bait Names`
- [x] In the Tableau report, add the additional column "Bait Names" to the right of the 'Library Type' column displaying the corresponding result from the database view.
- [x] Update Confluence page [here](https://ssg-confluence.internal.sanger.ac.uk/display/PSDPUB/Sample+Tracking+Report) if required

**Comment by khelwood** [comment]
@TWJW-SANGER What is the "query logic" that requires new columns to be added to the right of existing columns in the SQL view?

**Comment by TWJW-SANGER** [comment]
Discussed the above with David - yes I agree the position does not need to be on the right. 
I'll adjust the acceptance criteria.

**Comment by harrietc52** [comment]
# Deployment

UAT 

- [x] Run the `./apply` script, for UAT, to add the column to the database view
- [x] Tableau should run at 2am, to pull the latest view into the UAT Tableau report
- [x] In the UAT Tableau report, rename field from `bait_names` to `Bait Names`
- [ ] In the UAT Tableau report, add the additional column "Bait Names" to the right of the 'Library Type' column displaying the corresponding result from the database view.
- [ ] Save the UAT Tableau report 
- [ ] User testings
- [ ] Run the `./apply` script, for PRODUCTION, to add the column to the database view
- [ ] Tableau should run at 2am, to pull the latest view into the Production Tableau report
- [ ] In the Production Tableau report, rename field from `bait_names` to `Bait Names`
- [ ] In the Production Tableau report, add the additional column "Bait Names" to the right of the 'Library Type' column displaying the corresponding result from the database view.
- [ ] Save the the Production Tableau report

**Comment by harrietc52** [comment]
Some Feedback from the user

"I was just thinking that it would be useful information to include for end users on the confluence page - i.e on the table that describes what each event is, there could be an additional column to say when the column is populated.
If this becomes widely used by Scientists, I could see some panicking if they see their submission is down as being a pulldown type but there is no bait name, they may think it hasn't been specified or there's an error in the submission, but really it just hasn't reached the step in the process where that info is added."

**Comment by TWJW-SANGER** [comment]
The bait library field comes from the iseq_flowcell table whose rows are only created when sequencing submissions are created.
In common with the **Cost Code**, **Library Type** and **Platform** it will only be populated when sequencing is started.

This can be confirmed by looking at the UAT Tableau report for plates SQPP-20195-N and SQPP-22855-L (one of which has sequenced samples and a bait library name and the other does not).

I think all that needs doing is:

- [ ] Modifying the text on the Sample Tracking report at the top from "Cost Code, Platform, and Library Type values are not populated until sequencing has started" to "Cost Code, Platform, Library Type  and Bait Names values are not populated until sequencing has started"
- [ ] Adding a similar comment on the Confluence Page describing the fields in the Sample Tracking View.

**Comment by harrietc52** [comment]
Cleaned up the Tableau Data Source Connections for UAT and Prod. Described [here](https://github.com/sanger/sample-tracking/pull/35)
