### ISSUE TITLE
Y24-270 - As a CASM Project Mgr (LH) I would like to show the Programme and Faculty Sponsor associated with each plate so that individuals can quickly identify the plates they are interested in.

### ISSUE THREAD

**Issue by TWJW-SANGER** [sanger/sample-tracking#27]
**User story**
As a CASM Project Mgr (LH) I would like to show the Programme and Faculty Sponsor associated with each plate so that individuals can quickly identify the plates they are interested in.

**Who are the primary contacts for this story**
Laura H

**Who is the nominated tester for UAT**
Laura H

**Acceptance criteria**
To be considered successful the solution must allow:
- [ ] Display the Programme associated with each plate through the study table next to the right of study id in the reporting view.
- [ ] Display the Faculty Sponsor from the faculty_sponsor field in the study table to the right of the Programme in the reporting view.
- [ ] Display the Programme associated with each plate through the study table next to the right of study id in the Tableau report.
- [ ] Display the Faculty Sponsor from the faculty_sponsor field in the study table to the right of the Programme in the Tableau report.
- [ ] The Search functionality in the Tableau report will correctly pick up items in these columns.

**Dependencies**
This story is blocked by the following dependencies:
- sanger/sequencescape#4109

**Additional context**
